export function getRandomIdeas(n) {
  let ans = []
  for (let i = n; i > 0; i--) {
    ans.push(BASIC_IDEAS[Math.floor(Math.random() * BASIC_IDEAS.length)]);
    ans.push(MOTIVATIONS[Math.floor(Math.random() * MOTIVATIONS.length)]);
  }
  return ans.join(", ");
};


const BASIC_IDEAS = [
    "Dragon rider's quest",
    "Beast master's bond",
    "Gifted elementalist",
    "Summoned from another world",
    "Reborn as a villain",
    "Regressed to childhood",
    "Steamy office romance",
    "Forbidden love affair",
    "Harem of beast-kin",
    "Trapped in the abyss",
    "Demon king's return",
    "Forged mythical sword",
    "Goblin slayer's journey",
    "Slime's evolution",
    "Academy's top student",
    "Isekai'd as a farmer",
    "Second chance at life",
    "Time-traveling historian",
    "CEO's secret baby",
    "Teacher-student romance",
    "Succubus queen's harem",
    "Escaping the underworld",
    "Fallen angel's redemption",
    "Discovered ancient ruins",
    "Necromancer's apprentice",
    "Phoenix's rebirth",
    "Cursed bloodline",
    "Transported to a game",
    "Woke up in a novel",
    "Sent back in time",
    "Billionaire's fake marriage",
    "Alpha werewolf's mate",
    "Harem of goddesses",
    "Surviving purgatory",
    "Resurrected hero",
    "Found philosopher's stone",
    "Dungeon crawler's guide",
    "Spider monster's web",
    "Magic academy's secret",
    "Isekai'd with my smartphone",
    "Reincarnated with cheats",
    "Regressed with knowledge",
    "enemies to lovers",
    "Forbidden royal romance",
    "Harem of vampires",
    "Stuck between realms",
    "Demon lord's diary",
    "Wielding legendary shield",
    "Orc chieftain's rise",
    "Mutated creature",
    "Hidden magic society",
    "Isekai'd as a slime",
    "Reborn into nobility",
    "Regressed to save the world",
    "Contract relationship",
    "Vampire's forbidden love",
    "Harem of dragon girls",
    "Lost in the void",
    "Angel's fall from grace",
    "Found the holy grail",
    "Monster hunter's guild",
    "Sentient weapon",
    "Failed mage's comeback",
    "Isekai'd as a god",
    "Reincarnated as a princess",
    "Regressed to the apocalypse",
    "Childhood friends to lovers",
    "My stepbrother's secret",
    "Harem of monster girls",
    "Escape from Tartarus",
    "Reborn demon's ambition",
    "Found the cursed amulet",
    "Dwarf fortress builder",
    "Evolving monster",
    "Secret school of assassins",
    "Isekai'd with my truck",
    "Reborn as the villainess",
    "Regressed to prevent disaster",
    "Second lead's romance",
    "Forbidden priestess love",
    "Harem of angels",
    "Trapped in a time loop",
    "Demon king's human bride",
    "Wore the ring of power",
    "Undead king's reign",
    "My system is a goddess",
    "Genius inventor's workshop",
    "Isekai'd to a wasteland",
    "Reincarnated as my rival",
    "Regressed to the starting point",
    "Mafia boss's obsession",
    "Age gap romance",
    "Harem of fox spirits",
    "Stuck in a dream world",
    "The last dragon",
    "Forged the divine armor",
    "Lich's secret library",
    "Apocalypse survival guide",
    "Overpowered main character",
    "Isekai'd as a vending machine",
    "Reborn with all my memories",
    "Regressed to become a god",
    "Love triangle with brothers",
    "My boss is a vampire",
    "Harem of mermaids",
    "Lost in a fantasy world",
    "Demon lord's heir",
    "Found the dragon's egg",
    "Goblin kingdom rises",
    "Chimera's identity",
    "The alchemist's secret",
    "Isekai'd with a cheat skill",
    "Reincarnated as a tree",
    "Regressed to the past",
    "Forced cohabitation romance",
    "My forbidden stepsister",
    "Harem of dwarves",
    "Surviving a death game",
    "Fallen god's power",
    "Unlocked the legendary grimoire",
    "Building a monster army",
    "System administrator privileges",
    "Academy for the gifted",
    "Isekai'd to my favorite game",
    "Reborn as a commoner",
    "Regressed with future sight",
    "Childhood sweetheart returns",
    "Forbidden student romance",
    "Harem of cat girls",
    "Escaping a virtual reality",
    "The demon's contract",
    "Discovered a hidden village",
    "King of the undead",
    "My skills are maxed out",
    "The world's greatest swordsman",
    "Isekai'd to a cultivation world",
    "Reincarnated as a sword",
    "Regressed to my weakest state",
    "Fake dating the celebrity",
    "My roommate is a ghost",
    "Harem of witches",
    "Lost in the spirit realm",
    "The last of my kind",
    "Found Pandora's Box",
    "Monster evolution system",
    "Glitch in the system",
    "School for demigods",
    "Isekai'd with my class",
    "Reborn as a dungeon core",
    "Regressed to change my fate",
    "One-night stand with the prince",
    "My brother's best friend",
    "Harem of succubi",
    "Stuck in the fairy realm",
    "Rise of the demon king",
    "Wielding a cursed weapon",
    "Taming mythical beasts",
    "Eldritch horror's awakening",
    "The hidden heir",
    "Isekai'd as a healer",
    "Reincarnated as the demon lord",
    "Regressed to defeat the hero",
    "Contract marriage with the duke",
    "My teacher is an alien",
    "Harem of demons",
    "Trapped in an alternate dimension",
    "The angel's war",
    "Found the fountain of youth",
    "Building a kingdom",
    "My stats are bugged",
    "The ultimate martial artist",
    "Isekai'd as a noble",
    "Reborn as a phoenix",
    "Regressed to my graduation",
    "The billionaire's proposal",
    "In love with a ghost",
    "Harem of cyborgs",
    "Lost in a forgotten land",
    "The dragon's chosen",
    "Forged the ultimate weapon",
    "Taming wild dragons",
    "Awakened my powers",
    "The last spellcaster",
    "Isekai'd to a book",
    "Reincarnated as a goblin",
    "Regressed after dying",
    "The prince's secret lover",
    "My best friend's dad",
    "Harem of aliens",
    "Stuck in a cursed forest",
    "The gods are reborn",
    "Found the lost city",
    "Monster tamer's legacy",
    "System error",
    "The chosen one's destiny",
    "Isekai'd to a world of swords",
    "Reborn as a wolf",
    "Regressed to the academy",
    "The sheikh's captive",
    "My student is a vampire",
    "Harem of nymphs",
    "Escaping the labyrinth",
    "The demon queen's champion",
    "Wielding the staff of ages",
    "Summoning ancient gods",
    "My hidden potential",
    "The time traveler's paradox",
    "Isekai'd to ancient times",
    "Reincarnated as a spirit",
    "Regressed with a system",
    "The doctor's forbidden patient",
    "My new boss is my ex",
    "Harem of androids",
    "Lost in the astral plane",
    "The prophecy's child",
    "Found the map to El Dorado",
    "Goblin's evolution",
    "The system's chosen player",
    "The hero's betrayal",
    "Isekai'd to a world without magic",
    "Reborn as the hero's sister",
    "Regressed to the final battle",
    "The bodyguard's client",
    "My neighbor is a werewolf",
    "Harem of shifters",
    "Stuck in a haunted house",
    "The rise of the lich",
    "Found the necronomicon",
    "Taming the leviathan",
    "The forgotten magic",
    "The last dragon rider",
    "Isekai'd to a war",
    "Reincarnated as a noble's daughter",
    "Regressed to my birth",
    "The rock star's secret",
    "My childhood bully's love",
    "Harem of centaurs",
    "Trapped in a video game",
    "The vampire's curse",
    "Discovered a new element",
    "Monster city management",
    "The player's second life",
    "The academy's outcast",
    "Isekai'd with my pet",
    "Reborn as a dragon",
    "Regressed with alchemy",
    "The CEO's runaway bride",
    "My stepmother's son",
    "Harem of genies",
    "Lost in the abyss",
    "The god of slaughter",
    "Wielding the hammer of gods",
    "Taming the chimera",
    "The celestial's blessing",
    "The time mage's apprentice",
    "Isekai'd to a peaceful world",
    "Reincarnated as a monster",
    "Regressed to become a king",
    "The billionaire's secret heir",
    "My best friend is a demon",
    "Harem of harpies",
    "Stuck in the demon realm",
    "The archangel's fall",
    "Found the crystal skull",
    "Evolving my minions",
    "The game's final boss",
    "The failed hero's return",
    "Isekai'd to a desert island",
    "Reborn as a dungeon master",
    "Regressed to my childhood home",
    "The fake fiancée",
    "My sister's boyfriend",
    "Harem of gorgons",
    "Trapped in a painting",
    "The titan's awakening",
    "Forged the Excalibur",
    "Taming the kraken",
    "The bloodline's power",
    "The dimensional traveler",
    "Isekai'd as a blacksmith",
    "Reincarnated as a god's son",
    "Regressed to the tutorial",
    "The arranged marriage",
    "My ghost roommate",
    "Harem of lamias",
    "Lost in a hostile world",
    "The demon's chosen one",
    "Found the lost ark",
    "Building a monster empire",
    "The system's tutorial",
    "The hero's secret identity",
    "Isekai'd to the future",
    "Reborn as the villain's child",
    "Regressed to the beginning",
    "The prince's personal guard",
    "My professor is a werewolf",
    "Harem of sirens",
    "Stuck in a parallel universe",
    "The god's game",
    "Wielding the scythe of death",
    "Taming the hydra",
    "The forgotten lineage",
    "The space-time mage",
    "Isekai'd as a merchant",
    "Reincarnated as a familiar",
    "Regressed to save my family",
    "The billionaire's bodyguard",
    "My client is a vampire",
    "Harem of dryads",
    "Trapped in a simulation",
    "The last demigod",
    "Found the ancient codex",
    "Evolving my base",
    "The game's hidden class",
    "The academy's prodigy",
    "Isekai'd to a magic school",
    "Reborn as a hero's companion",
    "Regressed to the apocalypse's start",
    "The celebrity's secret girlfriend",
    "My landlord is a ghost",
    "Harem of valkyries",
    "Lost in the elemental planes",
    "The world serpent's awakening",
    "Found the legendary artifact",
    "Monster's skill tree",
    "The system's final quest",
    "The hero's second chance",
    "Isekai'd with creation powers",
    "Reincarnated as a spirit fox",
    "Regressed to my first dungeon",
    "The mafia's arranged marriage",
    "My best friend's older brother",
    "Harem of kitsune",
    "Stuck in a historical drama",
    "The primordial's return",
    "Wielding the sun sword",
    "Taming the griffin",
    "The awakened bloodline",
    "The portal jumper",
    "Isekai'd as a farmer's son",
    "Reborn as the protagonist",
    "Regressed to the age of gods",
    "The prince and the pauper",
    "My soulmate is a ghost",
    "Harem of oni",
    "Trapped in a fairy tale",
    "The demon lord's vessel",
    "Found the lost continent",
    "Evolving my slime",
    "The game's true ending",
    "The hero's dark secret",
    "Isekai'd to a world of gods",
    "Reincarnated as a shadow",
    "Regressed to my first life",
    "The billionaire's fake girlfriend",
    "My new neighbor is a demon",
    "Harem of djinn",
    "Lost in a cursed city",
    "The god's chosen warrior",
    "Forged the moon blade",
    "Taming the manticore",
    "The hidden prophecy",
    "The reality warper",
    "Isekai'd as a prince",
    "Reborn as a system",
    "Regressed with all my powers",
    "The contract lover",
    "My boss is a demon lord",
    "Harem of elementals",
    "Stuck in a death loop",
    "The last dragon's egg",
    "Found the tree of life",
    "Monster's evolution path",
    "The system's reward",
    "The hero's reincarnation",
    "Isekai'd with my memories",
    "Reincarnated as a star",
    "Regressed to the great war",
    "The secret billionaire",
    "My pet is a dragon",
    "Harem of gargoyles",
    "Trapped in another's body",
    "The cosmic entity",
    "Wielding the storm hammer",
    "Taming the thunderbird",
    "The fated encounter",
    "The dimensional merchant",
    "Isekai'd as a king",
    "Reborn as a dungeon",
    "Regressed to my weakest self",
    "The princess's knight",
    "My fiancé is a ghost",
    "Harem of golems",
    "Lost in the void sea",
    "The chosen's burden",
    "Found the city of gold"
];


const MOTIVATIONS = [
    "Family murdered by rivals",
    "Betrayed by a sibling",
    "Seeking a lost child",
    "To uphold the family name",
    "Father was a disgraced knight",
    "To prove a parent innocent",
    "Orphaned by a plague",
    "Sold into slavery by parents",
    "Last of a bloodline",
    "To escape a forced marriage",
    "Haunted by a family curse",
    "To avenge a spouse's death",
    "Protecting a younger sibling",
    "Inherited a massive debt",
    "Disowned for their choices",
    "Seeking their true parentage",
    "Mother died in childbirth",
    "To fulfill a dying wish",
    "Family exiled from homeland",
    "To break a generational cycle",
    "Raised by wolves",
    "Witnessed parents' assassination",
    "Forced to fight a sibling",
    "To save their ancestral home",
    "Searching for a kidnapped spouse",
    "Framed by a family member",
    "To continue the family business",
    "Haunted by their ancestors",
    "To escape their family's shadow",
    "Abused by a guardian",
    "Left for dead by family",
    "To find a cure for a sick child",
    "Seeking revenge on a stepparent",
    "Family honor was destroyed",
    "To reclaim their birthright",
    "Unwanted, abandoned child",
    "To protect a secret heir",
    "Family joined a cult",
    "To find a mythical homeland",
    "Watched their village burn",
    "Was a child soldier",
    "Survived a genocide",
    "Escaped a prison camp",
    "Tortured for information",
    "Lost a limb in battle",
    "Victim of a magical experiment",
    "Body possessed by a demon",
    "Mind shattered by an elder god",
    "Branded as an outcast",
    "Survived a shipwreck",
    "Left to die in the wilderness",
    "Publicly humiliated",
    "Lost their memory",
    "Incurable, fatal disease",
    "Cursed with immortality",
    "Hunted for their unique blood",
    "Saw the end of the world",
    "Survived a gladiatorial arena",
    "Forced to kill a loved one",
    "Used as a political pawn",
    "Stripped of their magic",
    "Mutated against their will",
    "Buried alive",
    "Psychologically broken",
    "Victim of a con artist",
    "Addicted to a substance",
    "Wrongfully imprisoned",
    "Lost everything in a fire",
    "Hunted by former allies",
    "To overcome a crippling fear",
    "Saw their god die",
    "To reverse a terrible mistake",
    "Haunted by their victims",
    "Body is a ticking time bomb",
    "To reclaim a stolen identity",
    "Desperate for power",
    "To achieve ultimate knowledge",
    "Wants to become a god",
    "Seeking legendary wealth",
    "To create a perfect world",
    "Driven by insatiable greed",
    "To prove everyone wrong",
    "Searching for true love",
    "Wants to be remembered forever",
    "To build a lasting empire",
    "Needs to feel in control",
    "To invent something revolutionary",
    "Seeking forbidden arts",
    "Wants to be the very best",
    "To earn their freedom",
    "Driven by pure hedonism",
    "To find a worthy opponent",
    "Wants to live a simple life",
    "To explore the unknown",
    "Seeking enlightenment",
    "To master a single skill",
    "Driven by artistic passion",
    "Wants to unite the clans",
    "To find the meaning of life",
    "Seeking a peaceful death",
    "To leave a legacy",
    "Wants to be loved",
    "To achieve perfection",
    "Driven by wanderlust",
    "To protect the innocent",
    "Wants to understand evil",
    "To create a masterpiece",
    "Seeking an honorable death",
    "To prove their own existence",
    "Wants to start a revolution",
    "Driven by a prophecy",
    "A holy crusade",
    "To spread their faith",
    "Fighting for social justice",
    "Apostate, hunted by their church",
    "Believes they are a chosen one",
    "To destroy a corrupt church",
    "Seeking political asylum",
    "A fanatic loyal to a king",
    "To overthrow a tyrant",
    "Wants to establish a democracy",
    "Anarchist seeking to topple all states",
    "To enforce a strict moral code",
    "Fighting for racial equality",
    "To preserve an ancient tradition",
    "Believes in might makes right",
    "Utilitarian, for the greater good",
    "Nihilist, believes in nothing",
    "To defend their homeland",
    "Seeking to create a utopia",
    "Believes technology is salvation",
    "Luddite, wants to destroy technology",
    "To fulfill a sacred vow",
    "Excommunicated for heresy",
    "To protect a holy relic",
    "Fighting for workers' rights",
    "A nationalist zealot",
    "To prove their god exists",
    "Seeking to debunk all religion",
    "To find a promised land",
    "Believes in destiny",
    "Wants to break the chains of fate",
    "Envies their rival's success",
    "Unrequited love",
    "Obsessed with a celebrity",
    "Stalking a former lover",
    "To win an arranged partner's love",
    "Blackmailed by an enemy",
    "Owes a life debt",
    "Lover was killed in a duel",
    "To save a friend from execution",
    "Betrayed by their best friend",
    "Their love is from a rival family",
    "In love with their superior officer",
    "Lover is from a different species",
    "To protect a mentor's secret",
    "Friend was magically erased",
    "In a love triangle",
    "To find their soulmate",
    "Their child was prophesied to be evil",
    "Lover is married to the king",
    "To save a captured comrade",
    "Friend became a monster",
    "Trying to impress someone",
    "Their love was kidnapped",
    "To avenge a fallen master",
    "Lover doesn't know they exist",
    "Committed a crime for a friend",
    "To save a pet",
    "Their mentor turned evil",
    "In love with an AI",
    "To join a prestigious guild",
    "Their hero became a villain",
    "Seeking redemption for past sins",
    "To atone for a moment of cowardice",
    "Wants to clear their name",
    "Haunted by a single failure",
    "To make amends with their family",
    "Trying to forgive themself",
    "To fix the damage they caused",
    "Wants to die with a clean conscience",
    "To undo a curse they cast",
    "Seeking forgiveness from someone",
    "To rebuild a destroyed village",
    "Wants to be a better person",
    "To pay back a moral debt",
    "Haunted by the ghost of their victim",
    "To restore what was stolen",
    "Trying to live up to an ideal",
    "To protect others from their own power",
    "Wants a second chance",
    "To reverse a deal with a demon",
    "Seeking absolution",
    "To destroy their own evil creation",
    "Wants to purify their soul",
    "To earn the trust of their allies",
    "Trying to escape their past",
    "To right a historical wrong",
    "Wants to be worthy of love",
    "To find peace of mind",
    "Entire civilization was wiped out",
    "Homeland is covered in ice",
    "To stop a spreading blight",
    "Their people live in crushing poverty",
    "A natural resource ran out",
    "To escape a dictatorial regime",
    "Their society is rigidly stratified",
    "To escape an incoming asteroid",
    "Hunted by the secret police",
    "Their culture is being erased",
    "A monster plagues their town",
    "Falsely accused of treason",
    "To escape a devastating war",
    "Their people were enslaved",
    "A magical cataclysm destroyed their home",
    "To warn others of a coming threat",
    "The sun is dying",
    "To find new territory for their people",
    "Their city is sinking",
    "To escape a society with no free will",
    "The stars are disappearing",
    "To break their nation's isolation",
    "Their world is a simulation",
    "To find a cure for a mass plague",
    "The law is unjust and cruel",
    "To escape a dying world",
    "Their gods have abandoned them",
    "To survive in a post-apocalyptic world",
    "The government controls all knowledge",
    "To seek aid from a stronger nation",
    "Born with a forbidden talent",
    "Is the last of their kind",
    "To win a grand tournament",
    "Seeks a legendary, lost city",
    "To translate ancient, forgotten texts",
    "They made a foolish bet",
    "To capture a mythical beast",
    "Wants to map the entire world",
    "To climb the highest mountain",
    "Is bored with their current life",
    "To steal a priceless artifact",
    "Wants to become a master chef",
    "To solve a famous unsolved mystery",
    "Heard a rumor of a magical spring",
    "Wants to join the circus",
    "To prove a scientific theory",
    "Is searching for a rare ingredient",
    "To perform on the grandest stage",
    "Wants to open their own tavern",
    "To create the ultimate weapon",
    "Is cataloging every living species",
    "To break a world record",
    "Wants to find the edge of the world",
    "To get revenge for a petty insult",
    "Is writing the ultimate epic",
    "To debunk a local legend",
    "Wants to become a pirate king",
    "To pay for life-saving surgery",
    "Is simply a thrill-seeker",
    "To collect a bounty",
    "Wants to build the fastest ship",
    "To earn a noble title",
    "Is looking for a good story",
    "Wants to see a specific wonder",
    "To protect a rare animal",
    "Is on a pilgrimage",
    "To find a worthy successor",
    "Wants to learn a secret technique",
    "To pay off a gambling debt",
    "Is trying to outrun a prophecy",
    "To deliver an important message",
    "Just wants to go home",
    "To fulfill a contract",
    "Wants to find a place to belong",
    "To explore a newly discovered continent",
    "Is running from the law",
    "To find a plant that grants wishes",
    "Wants to be a great artist",
    "To get revenge on a school bully",
    "Is searching for a ghost ship",
    "Wants to own their own land",
    "To prove that monsters are real",
    "Is on the run from a guild",
    "Wants to publish a controversial book",
    "To find a lost library",
    "Is being blackmailed",
    "To win the affection of a noble",
    "Wants to die in a famous battle",
    "To start a new colony",
    "Is looking for a peaceful retirement",
    "Wants to see the ocean",
    "To solve their own murder",
    "Wants to become a ghost",
    "To learn the language of animals",
    "Is trying to find a lost love",
    "Wants to see a volcano erupt",
    "To create a new form of life",
    "Is training for a great race",
    "Wants to become a master diplomat",
    "To avenge their own humiliation",
    "Is on a quest for a magical instrument",
    "Wants to find a fountain of youth",
    "To pay for a sibling's education",
    "Is being hunted by a creature",
    "To find their long-lost twin",
    "Wants to see the world from the sky",
    "To destroy a cursed object",
    "Is competing in a deadly game",
    "Wants to become a spymaster",
    "To find the components for a ritual",
    "Is escaping an arranged life",
    "Wants to understand the gods",
    "To protect a small community",
    "Is searching for a lost civilization",
    "Wants to build a great bridge",
    "To find a magical sword",
    "Is paying for their crimes",
    "Wants to become a folk hero",
    "To learn the secrets of the cosmos",
    "Is seeking a legendary teacher",
    "Wants to be the richest person alive",
    "To prove they are not a coward",
    "Is on a quest from their deity",
    "Wants to find a place they saw in a dream",
    "To bring magic back to the world",
    "Is trying to prevent a war",
    "Wants to become a judge",
    "To find a cure for their amnesia",
    "Is hunting down a notorious criminal",
    "Wants to live without fear",
    "To reclaim a conquered homeland",
    "Is looking for a magical creature's aid",
    "To become the royal advisor",
    "Wants to build a safe haven",
    "To find the last dragon",
    "Is cursed to wander forever",
    "Wants to travel through time",
    "To find a new source of energy",
    "Is trying to stop an apocalypse",
    "Wants to become a master thief",
    "To find an artifact that controls weather",
    "Is escaping a toxic relationship",
    "Wants to live in the wilderness",
    "To find the creator of the universe",
    "Is bound to serve a magical master",
    "Wants to become the head of a guild",
    "To learn the art of healing",
    "Is searching for a forgotten god",
    "Wants to see their child grow up",
    "To assassinate a corrupt leader",
    "Is on the run with secret information",
    "Wants to start a family",
    "To find a way to communicate with the dead",
    "Is trying to unite warring factions",
    "Wants to become a champion of the people",
    "To find a weapon that can kill a god",
    "Is fulfilling a promise to a dead friend",
    "Wants to experience every pleasure",
    "To find the source of all magic",
    "Is repaying a kindness",
    "Wants to build a perfect machine",
    "To prove their sanity",
    "Is searching for a lost piece of music",
    "Wants to live a life of adventure",
    "To understand their own strange powers",
    "Is bound by an unbreakable oath",
    "Wants to find a place where they are accepted",
    "To destroy an evil organization",
    "Is seeking a legendary smith",
    "Wants to be free from all responsibility",
    "To find a way to bring someone back to life",
    "Is searching for the truth",
    "Wants to die",
    "To find a new god to worship",
    "Is protecting the last of a species",
    "Wants to be completely anonymous",
    "To find and defeat their master",
    "Is searching for a gate to another world",
    "Wants to see their enemies fall",
    "To create a work of art that will last forever",
    "Is looking for a quiet place to read",
    "Wants to be a parent",
    "To find an object that can answer any question",
    "Is seeking revenge on society itself",
    "Wants to understand their own heart",
    "To prove that peace is possible",
    "Is on a journey of self-discovery",
    "Wants to be remembered as a hero",
    "To find a way to control their dreams",
    "Is searching for a person from their past",
    "Wants to learn every language",
    "To end all suffering",
    "Is trying to escape their own destiny",
    "Wants to be forgiven",
    "To find a new home for their people",
    "Is looking for a challenge",
    "Wants to be the one who decides",
    "To protect a secret that could destroy the world",
    "Is searching for a mythical herb",
    "Wants to build a library of all knowledge",
    "To find a way to fly",
    "Is trying to stop a magical plague",
    "Wants to be the power behind the throne",
    "To find a lost family heirloom",
    "Is escaping a prophecy about themself",
    "Wants to live a life of consequence",
    "To understand the nature of reality",
    "Is bound to protect a certain place",
    "Wants to be known for their wisdom",
    "To find a way to be young forever",
    "Is searching for a lost love's grave",
    "Wants to see justice done",
    "To prevent a future they foresaw",
    "Is trying to redeem their family's name",
    "Wants to be forgotten by everyone",
    "To find a way to heal the land",
    "Is seeking a master of disguise",
    "Wants to live a life full of laughter",
    "To destroy a powerful, evil artifact",
    "Is looking for someone to take their place",
    "Wants to be a kingmaker",
    "To find the truth behind a conspiracy",
    "Is escaping the monotony of their life",
    "Wants to be a master strategist",
    "To find a way to share their consciousness",
    "Is trying to save their own soul",
    "Wants to be the last one standing",
    "To find a way to make everyone happy"
];