export function getRandomNames(n) {
  let ans = []
  for (let i = n; i > 0; i--)
    ans.push(FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)]);
  for (let i = n; i > 0; i--)
    ans.push(LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)]);
  for (let i = n / 5; i > 0; i--)
    ans.push(COUNTRY_NAMES[Math.floor(Math.random() * COUNTRY_NAMES.length)]);
  for (let i = n / 5; i > 0; i--)
    ans.push(CITY_NAMES[Math.floor(Math.random() * CITY_NAMES.length)]);

  return ans.join(", ");
};


const FIRST_NAMES = [
    "Liam",
    "Noah",
    "Oliver",
    "James",
    "Elijah",
    "William",
    "Henry",
    "Lucas",
    "Benjamin",
    "Theodore",
    "Mateo",
    "Levi",
    "Sebastian",
    "Daniel",
    "Jack",
    "Michael",
    "Alexander",
    "Owen",
    "Asher",
    "Samuel",
    "Ethan",
    "Leo",
    "Jackson",
    "Mason",
    "Ezra",
    "John",
    "Hudson",
    "Luca",
    "Aiden",
    "Joseph",
    "David",
    "Jacob",
    "Waylon",
    "Thomas",
    "Matthew",
    "Luke",
    "Julian",
    "Grayson",
    "Levi",
    "Christopher",
    "Isaac",
    "Isaiah",
    "Miles",
    "Maverick",
    "Anthony",
    "Cooper",
    "Muhammad",
    "Wyatt",
    "Caleb",
    "Carter",
    "Josiah",
    "Charles",
    "Jayden",
    "Nathan",
    "Gabriel",
    "Logan",
    "Christian",
    "Jonathan",
    "Roman",
    "Dylan",
    "Adam",
    "Andrew",
    "Jaxon",
    "Joshua",
    "Angel",
    "Lincoln",
    "Adrian",
    "Eli",
    "Ryan",
    "Ian",
    "Brooks",
    "Axel",
    "Walker",
    "Nolan",
    "Ezra",
    "Weston",
    "Ezekiel",
    "Cameron",
    "Theodore",
    "Elias",
    "Colton",
    "Austin",
    "Robert",
    "Jameson",
    "Everett",
    "Greyson",
    "Wesley",
    "Jeremiah",
    "Hunter",
    "Jordan",
    "Jose",
    "Bennett",
    "Kai",
    "Beau",
    "Aaron",
    "Micah",
    "Silas",
    "Harrison",
    "Rowan",
    "Jason",
    "Xavier",
    "Parker",
    "Dominic",
    "Kayden",
    "Miles",
    "Vincent",
    "Leonardo",
    "August",
    "Evan",
    "Graham",
    "Zayden",
    "George",
    "Calvin",
    "Kingston",
    "Archer",
    "Sawyer",
    "Enzo",
    "Zion",
    "John",
    "Edward",
    "Josue",
    "Jesus",
    "Kevin",
    "Emmett",
    "Brody",
    "Jude",
    "Abel",
    "King",
    "Jonah",
    "Amir",
    "Declan",
    "Malachi",
    "Milo",
    "Timothy",
    "Ezequiel",
    "Damian",
    "Messiah",
    "Ace",
    "Legend",
    "River",
    "Ivan",
    "Luis",
    "Mark",
    "Jax",
    "Thiago",
    "Gael",
    "Brian",
    "Steven",
    "Kaleb",
    "Arthur",
    "Juan",
    "Cole",
    "Richard",
    "Preston",
    "Abram",
    "Joel",
    "Omar",
    "Diego",
    "Kenneth",
    "Marcus",
    "Miguel",
    "Abel",
    "Amari",
    "Caden",
    "Carlos",
    "Edward",
    "Felix",
    "Leon",
    "Max",
    "Patrick",
    "Paul",
    "Ryker",
    "Alan",
    "Alex",
    "Brady",
    "Colin",
    "David",
    "Eric",
    "Gary",
    "Isaac",
    "Jake",
    "Javier",
    "Jorge",
    "Justin",
    "Kyle",
    "Larry",
    "Oscar",
    "Peter",
    "Philip",
    "Quinn",
    "Raul",
    "Reid",
    "Riley",
    "Scott",
    "Seth",
    "Simon",
    "Spencer",
    "Tanner",
    "Taylor",
    "Titus",
    "Troy",
    "Tyler",
    "Victor",
    "Wade",
    "Walter",
    "Warren",
    "Wayne",
    "Will",
    "Xander",
    "Yusuf",
    "Zachary",
    "Zane",
    "Zayn",
    "Olivia",
    "Emma",
    "Charlotte",
    "Amelia",
    "Sophia",
    "Isabella",
    "Ava",
    "Mia",
    "Evelyn",
    "Luna",
    "Harper",
    "Camila",
    "Sofia",
    "Scarlett",
    "Elizabeth",
    "Eleanor",
    "Emily",
    "Chloe",
    "Mila",
    "Violet",
    "Penelope",
    "Gianna",
    "Aria",
    "Abigail",
    "Ella",
    "Avery",
    "Hazel",
    "Nora",
    "Lily",
    "Aurora",
    "Nova",
    "Ellie",
    "Madison",
    "Grace",
    "Isla",
    "Willow",
    "Zoe",
    "Riley",
    "Stella",
    "Eliana",
    "Naomi",
    "Victoria",
    "Everly",
    "Hannah",
    "Layla",
    "Leah",
    "Lucy",
    "Paisley",
    "Addison",
    "Aubrey",
    "Autumn",
    "Brooklyn",
    "Delilah",
    "Emilia",
    "Everleigh",
    "Genesis",
    "Madelyn",
    "Maya",
    "Natalia",
    "Quinn",
    "Savannah",
    "Serenity",
    "Skylar",
    "Zoey",
    "Aaliyah",
    "Adalynn",
    "Alice",
    "Amara",
    "Andrea",
    "Anna",
    "Ariana",
    "Aubree",
    "Audrey",
    "Bella",
    "Brielle",
    "Caroline",
    "Clara",
    "Cora",
    "Daisy",
    "Elena",
    "Eva",
    "Faith",
    "Gabriella",
    "Genevieve",
    "Georgia",
    "Hadley",
    "Hailey",
    "Isabelle",
    "Josephine",
    "Julia",
    "Juliana",
    "Juliette",
    "Katherine",
    "Kaylee",
    "Kennedy",
    "Kinsley",
    "Laila",
    "Lainey",
    "Leilani",
    "Lillian",
    "Lydia",
    "Mackenzie",
    "Madeline",
    "Maria",
    "Melanie",
    "Melody",
    "Mya",
    "Naomi",
    "Nevaeh",
    "Nicole",
    "Paige",
    "Peyton",
    "Piper",
    "Reagan",
    "Rose",
    "Ruby",
    "Sadie",
    "Samantha",
    "Sarah",
    "Sienna",
    "Sophie",
    "Taylor",
    "Trinity",
    "Valentina",
    "Valeria",
    "Valerie",
    "Vivian",
    "Willow",
    "Ximena",
    "Yara",
    "Zara",
    "Zuri",
    "Adeline",
    "Alaina",
    "Alanis",
    "Alayah",
    "Aleah",
    "Alejandra",
    "Alena",
    "Alessandra",
    "Alessia",
    "Alex",
    "Alexa",
    "Alexandra",
    "Alexia",
    "Alexis",
    "Alia",
    "Aliana",
    "Alina",
    "Alivia",
    "Aliyah",
    "Allison",
    "Allyson",
    "Alyssa",
    "Amaia",
    "Amani",
    "Amari",
    "Amaris",
    "Amayah",
    "Amelie",
    "Amina",
    "Amira",
    "Amy",
    "Ana",
    "Anahi",
    "Analia",
    "Anastasia",
    "Anaya",
    "Andi",
    "Angel",
    "Angela",
    "Angelica",
    "Angelina",
    "Anika",
    "Aniya",
    "Aniyah",
    "Annabelle",
    "Annalise",
    "Anne",
    "Annette",
    "Annie",
    "Antonella",
    "April",
    "Arabella",
    "Arely",
    "Ari",
    "Aria",
    "Ariah",
    "Ariana",
    "Arianna",
    "Ariel",
    "Ariella",
    "Arielle",
    "Ariya",
    "Ariyah",
    "Arlette",
    "Arya",
    "Ashlyn",
    "Aspen",
    "Athena",
    "Aubree",
    "Aubriella",
    "Audrey",
    "August",
    "Aurelia",
    "Aurora",
    "Austin",
    "Autumn",
    "Ava",
    "Avah",
    "Avani",
    "Avayah",
    "Averi",
    "Averie",
    "Avery",
    "Aviana",
    "Ayana",
    "Ayla",
    "Azalea",
    "Azaria",
    "Bailee",
    "Bailey",
    "Barbara",
    "Baylee",
    "Beatrice",
    "Belen",
    "Bella",
    "Belle",
    "Berenice",
    "Bethany",
    "Bexley",
    "Bianca",
    "Blair",
    "Blake",
    "Blakely",
    "Bonnie",
    "Braelynn",
    "Brantley",
    "Brenda",
    "Brenna",
    "Briana",
    "Brianna",
    "Bridget",
    "Briella",
    "Brielle",
    "Bristol",
    "Brittany",
    "Brooke",
    "Brooklyn",
    "Brooklynn",
    "Brylee",
    "Brynlee",
    "Cadence",
    "Cali",
    "Callie",
    "Cameron",
    "Camila",
    "Camille",
    "Camryn",
    "Cara",
    "Carla",
    "Carlee",
    "Carley",
    "Carly",
    "Carmen",
    "Carolina",
    "Caroline",
    "Carolyn",
    "Carter",
    "Casey",
    "Cassandra",
    "Cassidy",
    "Cataleya",
    "Catalina",
    "Catherine",
    "Caylee",
    "Cecelia",
    "Cecilia",
    "Celeste",
    "Celine",
    "Chana",
    "Chanel",
    "Charlee",
    "Charleigh",
    "Charli",
    "Charlie",
    "Charlotte",
    "Chaya",
    "Chelsea",
    "Cheyenne",
    "Chloe",
    "Christina",
    "Christine",
    "Claire",
    "Clara",
    "Clare",
    "Clarissa",
    "Claudia",
    "Clementine",
    "Colette",
    "Collins",
    "Cora",
    "Coraline",
    "Corinne",
    "Crystal",
    "Cynthia"
];


const LAST_NAMES = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennet",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
    "Powell",
    "Jenkins",
    "Perry",
    "Russell",
    "Sullivan",
    "Bell",
    "Coleman",
    "Butler",
    "Henderson",
    "Barnes",
    "Gonzales",
    "Fisher",
    "Vasquez",
    "Simmons",
    "Romero",
    "Jordan",
    "Patterson",
    "Alexander",
    "Hamilton",
    "Graham",
    "Reynolds",
    "Griffin",
    "Wallace",
    "Moreno",
    "West",
    "Cole",
    "Hayes",
    "Bryant",
    "Herrera",
    "Gibson",
    "Ellis",
    "Tran",
    "Medina",
    "Aguilar",
    "Stevens",
    "Murray",
    "Ford",
    "Castro",
    "Marshall",
    "Owens",
    "Harrison",
    "Fernandez",
    "Mcdonald",
    "Woods",
    "Washington",
    "Kennedy",
    "Wells",
    "Vargas",
    "Henry",
    "Chen",
    "Freeman",
    "Webb",
    "Tucker",
    "Guzman",
    "Burns",
    "Crawford",
    "Olson",
    "Simpson",
    "Porter",
    "Hunter",
    "Hicks",
    "Wheeler",
    "Shaw",
    "Payne",
    "Wagner",
    "Stephens",
    "Weaver",
    "Matthews",
    "Warren",
    "Fox",
    "Johnston",
    "Arnold",
    "Soto",
    "Rios",
    "Rice",
    "Cooper",
    "Dunn",
    "Berry",
    "Lawrence",
    "Spencer",
    "Stanley",
    "Holland",
    "Hawkins",
    "Hart",
    "Cunningham",
    "Bradley",
    "Lane",
    "Andrews",
    "Ruiz",
    "Riley",
    "Hanson",
    "Alvarado",
    "Garza",
    "Scott",
    "Stone",
    "Snyder",
    "Mason",
    "Dixon",
    "Lynch",
    "Hunt",
    "Elliott",
    "Chambers",
    "Cain",
    "Day",
    "Gregory",
    "Mendez",
    "Grant",
    "Frazier",
    "Mcbride",
    "Santana",
    "Richards",
    "Bates",
    "Black",
    "Nash",
    "Serrano",
    "Beck",
    "Hudson",
    "Mills",
    "Meyer",
    "Daniels",
    "Bush",
    "Vaughn",
    "Parks",
    "Graves",
    "Garrett",
    "Walters",
    "Holmes",
    "Luna",
    "Figueroa",
    "Jacobs",
    "Rivas",
    "Carr",
    "Salazar",
    "Larson",
    "Pierce",
    "Casey",
    "Lloyd",
    "Vega",
    "Walsh",
    "Valdez",
    "Boyd",
    "Harper",
    "Patrick",
    "Little",
    "Sutton",
    "Olsen",
    "Mann",
    "Caldwell",
    "Padilla",
    "Newton",
    "Carroll",
    "Ortega",
    "Barrett",
    "Swanson",
    "Curtis",
    "Holt",
    "Barton",
    "Pope",
    "Goodwin",
    "Mack",
    "Paul",
    "Hopkins",
    "Mullins",
    "Fleming",
    "Jensen",
    "Hale",
    "Ballard",
    "Bishop",
    "Cortez",
    "Ray",
    "Pittman",
    "Stark",
    "Bauer",
    "Lamb",
    "Chung",
    "Sharp",
    "Fields",
    "Gross",
    "Lucas",
    "Hale",
    "Manning",
    "Valenzuela",
    "Bean",
    "Lyons",
    "Goodman",
    "May",
    "Abbott",
    "Pena",
    "Zimmerman",
    "Ball",
    "Todd",
    "Leonard",
    "Conner",
    "Maldonado",
    "Townsend",
    "Chang",
    "Blake",
    "Montoya",
    "Pham",
    "Haynes",
    "Heath",
    "Hodges",
    "Mcgee",
    "Neal",
    "Pearson",
    "Robles",
    "Yates",
    "Atkins",
    "Wilkerson",
    "Merritt",
    "Love",
    "Bray",
    "Flowers",
    "Pollard",
    "Hardy",
    "Cobb",
    "O'neill",
    "Moody",
    "Singleton",
    "Kirkland",
    "Ochoa",
    "Estrada",
    "Bernard",
    "Cervantes",
    "Barber",
    "Brewer",
    "Wolfe",
    "Bond",
    "Gaines",
    "French",
    "Watts",
    "Hinton",
    "Rowe",
    "Hogan",
    "Ibarra",
    "Solis",
    "Foley",
    "Randall",
    "Fry",
    "Crosby",
    "Winters",
    "Small",
    "Glover",
    "Weiss",
    "Chase",
    "Aguirre",
    "Ware",
    "Summers",
    "Salas",
    "Bradford",
    "Cannon",
    "Downs",
    "Hampton",
    "Pace",
    "Poole",
    "Savage",
    "Kline",
    "Farrell",
    "Hester",
    "Shields",
    "Key",
    "Horn",
    "Rosario",
    "Yu",
    "Dickerson",
    "Shepherd",
    "Oneal",
    "Mcconnell",
    "Hatfield",
    "Horton",
    "Lowery",
    "House",
    "Pruitt",
    "Nielsen",
    "Best",
    "Mccarthy",
    "Franco",
    "Dorsey",
    "Combs",
    "Daugherty",
    "Hoover",
    "Leblanc",
    "Huffman",
    "Frost",
    "Bright",
    "Flynn",
    "Powers",
    "Doyle",
    "Sweeney",
    "Brock",
    "Mercado",
    "Buckley",
    "Donovan",
    "Weeks",
    "Eaton",
    "Waller",
    "Short",
    "Mcintyre",
    "Kramer",
    "Gallegos",
    "Charles",
    "Gentry",
    "Mcclain",
    "Ho",
    "Ayers",
    "Harmon",
    "Rowland",
    "Dalton",
    "Mooney",
    "Holder",
    "Duke",
    "O'donnell",
    "Macias",
    "Finley",
    "Stanton",
    "Strong",
    "Whitney",
    "Osborne",
    "Mckenzie",
    "Potts",
    "Livingston",
    "Pugh",
    "Britt",
    "Morse",
    "Knox",
    "Fischer",
    "Huynh",
    "Buck",
    "Robbins",
    "Chan",
    "Burch",
    "Hardin",
    "Herman",
    "Cooley",
    "Singleton",
    "Clayton",
    "Kirk",
    "Spears",
    "Marks",
    "Estes",
    "English",
    "Villarreal",
    "Stout",
    "Hendricks",
    "Lara",
    "Dodson",
    "Meadows",
    "Carey",
    "Pacheco",
    "Haney",
    "Clements",
    "Stephens",
    "Conley",
    "Waters",
    "Mccoy",
    "Benson",
    "Byrd",
    "Cummings",
    "Noble",
    "Fletcher",
    "Holman",
    "Schultz",
    "Moody",
    "Burnett",
    "Underwood",
    "Baldwin",
    "Woodward",
    "Blankenship",
    "Reese",
    "Erickson",
    "Mcneil",
    "Wall",
    "Randolph",
    "Branch",
    "Sweet",
    "Rich",
    "Talley",
    "Mercer",
    "Gould",
    "Dudley",
    "Farley",
    "Hubbard",
    "Blanchard",
    "Roach",
    "Hendrix",
    "Hutchinson",
    "Sheppard",
    "Carrillo",
    "Tate",
    "Wooten",
    "Mckee",
    "Correa",
    "Lynn",
    "Kaufman"
];

const COUNTRY_NAMES = [
    "Roana Republic",
    "Adelia Kingdom",
    "Dragon Nation",
    "Demon Theocracy",
    "Gryphon's Aerie",
    "Kraken's Deep",
    "Phoenix Ascendancy",
    "Cyclopean Isles",
    "Celestial Concordance",
    "Shadow Syndicate",
    "Sunstone Empire",
    "Moonfall Queendom",
    "Starfall Confederacy",
    "Aetherium Expanse",
    "Netherworld Dominion",
    "Fire Drake Sultanate",
    "Sea Serpent's Domain",
    "Roc's Eyrie",
    "Leviathan's Trench",
    "Behemoth's Caldera",
    "Chimera's Crag",
    "Hydra's Marshland",
    "Pegasus' Meadow",
    "Unicorn's Glade",
    "Manticore's Lair",
    "Treant's Forest",
    "Nymph's Spring",
    "Satyr's Thicket",
    "Dryad's Grove",
    "Aloria Principality",
    "Eldoria Duchy",
    "Valoria Kingdom",
    "Solara Dominion",
    "Veridia Republic",
    "Aerthos Theocracy",
    "Lyra Queendom",
    "Gryff Barony",
    "Silver Coast Archduchy",
    "Sunstone Electorate",
    "Azure River Palatinate",
    "Crimson Forest March",
    "Iron Hills Landgraviate",
    "Golden Plains Protectorate",
    "Jade Isles Commonwealth",
    "Northern Baronies",
    "Western Kingdoms",
    "Eastern Principalities",
    "Southern Concordat",
    "Sunken Lands Republic",
    "Ashen Plains Nation",
    "Whispering Sands Dominion",
    "Silent Valleys Commonwealth",
    "Frozen North Kingdom",
    "Endless Steppe Theocracy",
    "Distant Shores Protectorate",
    "Crimson Forest Union",
    "Azure River Empire",
    "Iron Hills Confederacy",
    "Golden Plains Sovereignty",
    "Jade Isles Queendom",
    "Silver Coast Principality",
    "Sunstone Peaks Electorate",
    "Dragon's Gate Territory",
    "Wolf's Wood Barony",
    "Southern Marshes Duchy",
    "River Delta Shogunate",
    "Iron Mountains Sultanate",
    "Azure Bay Caliphate",
    "Seven Isles Emirate",
    "Whispering Peaks Tsardom",
    "Sundered Throne Khanate",
    "Volcanic Reach Republic",
    "Glacial Spire Nation",
    "Verdant Canopy Federation",
    "Mistwood Kingdom",
    "Shadowfen Theocracy",
    "Cinderfall Protectorate",
    "Starfall Desert Union",
    "Deepholm Confederacy",
    "Briarwood Thicket Barony",
    "Sunken City-State",
    "Terra Firma Concord",
    "Molten Heart Dominion",
    "Tidal Lock Nation",
    "Shifting Sands Sovereignty",
    "Republic of Solitude",
    "Nation of Concord",
    "Federation of Zenith",
    "Dominion of Dusk",
    "Commonwealth of Dawn",
    "Kingdom of Serenity",
    "Theocracy of Virtue",
    "Protectorate of Valor",
    "Union of Harmony",
    "Empire of Silence",
    "Confederacy of Echoes",
    "Sovereignty of Memory",
    "Queendom of Dreams",
    "Principality of Hope",
    "Barony of Despair",
    "Duchy of Regret",
    "Shogunate of Fate",
    "Sultanate of Fortune",
    "Caliphate of Wisdom",
    "Emirate of Knowledge",
    "Tsardom of Power",
    "Khanate of Glory",
    "Republic of Freedom",
    "Nation of Justice",
    "Federation of Equality",
    "Dominion of Order",
    "Commonwealth of Chaos",
    "Kingdom of Light",
    "Theocracy of Darkness",
    "Protectorate of Twilight",
    "Union of Balance",
    "Empire of Eternity",
    "Confederacy of Infinity",
    "Sovereignty of Beginnings",
    "Queendom of Endings",
    "Principality of Change",
    "Barony of Stasis",
    "Duchy of Growth",
    "Shogunate of Decay",
    "Sultanate of Creation",
    "Caliphate of Destruction",
    "Emirate of Life",
    "Tsardom of Death",
    "Khanate of Rebirth",
    "Republic of the Penitent",
    "Nation of the Forsaken",
    "Federation of the Exiled",
    "Dominion of the Ascended",
    "Commonwealth of the Fallen",
    "Kingdom of the Lost",
    "Silver Serpent Sovereignty",
    "Obsidian Eagle Empire",
    "Crimson Lion Confederacy",
    "Golden Phoenix Republic",
    "Azure Bear Union",
    "Iron Wolf Protectorate",
    "Sunstone Tortoise Kingdom",
    "Moonshadow Fox Theocracy",
    "Starfall Stag Dominion",
    "Stormcrow Barony",
    "Bloodhawk Duchy",
    "Celestial Whale Pod",
    "Infernal Scorpion Swarm",
    "Aetherial Serpent Coil",
    "Onyx Citadel Protectorate",
    "Emerald Throne Queendom",
    "Ruby Heart Confederacy",
    "Sapphire Shield Republic",
    "Diamond Mind Union",
    "Topaz Eye Kingdom",
    "Amethyst Crown Theocracy",
    "Garnet Hand Dominion",
    "Pearl Fang Barony",
    "Republic of Aeridor",
    "Kingdom of Valerium",
    "Empire of Solara",
    "Theocracy of Xylos",
    "Dominion of Veridia",
    "Confederacy of Lyra",
    "Union of Eldoria",
    "Protectorate of Gryff",
    "Sovereignty of Aloria",
    "Caelus's Queendom",
    "Aquaria's Principality",
    "Terranum's Barony",
    "Ignis's Duchy",
    "Aer's Shogunate",
    "Sylva's Sultanate",
    "Umbra's Caliphate",
    "Lux's Emirate",
    "Nox's Tsardom",
    "Tempus's Khanate",
    "Aethelgard's Republic",
    "Brythonia's Kingdom",
    "Cymeria's Empire",
    "Dumnonia's Theocracy",
    "Elmet's Dominion",
    "Fianna's Confederacy",
    "Gododdin's Union",
    "Hwicce's Protectorate",
    "Ivernia's Sovereignty",
    "Jute's Queendom",
    "Kernow's Principality",
    "Lindsey's Barony",
    "Mercia's Duchy",
    "Northumbria's Shogunate",
    "Orkney's Sultanate",
    "Powys's Caliphate",
    "Rheged's Emirate",
    "Strathclyde's Tsardom",
    "Thanet's Khanate",
    "Verlamion's Republic",
    "Waeclingas's Kingdom",
    "Yarrow's Empire",
    "Zennor's Theocracy",
    "Azure Concord Republic",
    "Crimson Pact Kingdom",
    "Golden Accord Empire",
    "Silver Covenant Theocracy",
    "Iron Vow Dominion",
    "Verdant Oath Confederacy",
    "Obsidian Pledge Union",
    "Sunstone Promise Protectorate",
    "Moonshadow Compact Sovereignty",
    "Starfall Treaty Queendom",
    "Stormwind Alliance Principality",
    "Whisperwood League Barony",
    "Thundertop Entente Duchy",
    "Shadowfen Concordat Shogunate",
    "Cinderfall Agreement Sultanate",
    "Ashen Covenant Caliphate",
    "Crystal Compact Emirate",
    "Barony of Solitude",
    "Duchy of Concord",
    "Shogunate of Zenith",
    "Sultanate of Dusk",
    "Caliphate of Dawn",
    "Emirate of Serenity",
    "Tsardom of Virtue",
    "Khanate of Valor",
    "Republic of Harmony",
    "Kingdom of Silence",
    "Empire of Echoes",
    "Theocracy of Memory",
    "Dominion of Dreams",
    "Confederacy of Hope",
    "Union of Despair",
    "Protectorate of Regret",
    "Sovereignty of Fate",
    "Queendom of Fortune",
    "Principality of Wisdom",
    "Barony of Knowledge",
    "Duchy of Power",
    "Shogunate of Glory",
    "Sultanate of Freedom",
    "Caliphate of Justice",
    "Emirate of Equality",
    "Tsardom of Order",
    "Khanate of Chaos",
    "Republic of Light",
    "Kingdom of Darkness",
    "Empire of Twilight",
    "Theocracy of Balance",
    "Dominion of Eternity",
    "Confederacy of Infinity",
    "Union of Beginnings",
    "Protectorate of Endings",
    "Sovereignty of Change",
    "Queendom of Stasis",
    "Principality of Growth",
    "Barony of Decay",
    "Duchy of Creation",
    "Shogunate of Destruction",
    "Sultanate of Life",
    "Caliphate of Death",
    "Emirate of Rebirth",
    "Tsardom of the Penitent",
    "Khanate of the Forsaken",
    "Republic of the Exiled",
    "Kingdom of the Ascended",
    "Empire of the Fallen",
    "Theocracy of the Lost",
    "Aeridor's Republic",
    "Valerium's Kingdom",
    "Solara's Empire",
    "Xylos's Theocracy",
    "Veridia's Dominion",
    "Lyra's Confederacy",
    "Eldoria's Union",
    "Gryff's Protectorate",
    "Aloria's Sovereignty",
    "Republic of the Final Dawn",
    "Kingdom of the First Light",
    "Empire of the Last Breath",
    "Theocracy of the Silent Word",
    "Glimmering Coast",
    "Shattered Isles",
    "Verdant Reach",
    "Whispering Isles",
    "Frozen Spire",
    "Ashen Wastes",
    "Emberwood",
    "Shadowfen",
    "Crystal Veins",
    "Iron Marches",
    "Golden Vale",
    "Silver Spire",
    "Crimson Reach",
    "Azure Deep",
    "Obsidian Plain",
    "Dragon's Maw",
    "Griffin's Rest",
    "Siren's Bay",
    "Wyrm's Tooth",
    "Titan's Fall",
    "Serpent's Coil",
    "Raven's Roost",
    "Wolf's Run",
    "Bear's Claw",
    "Eagle's Crest",
    "Lion's Pride",
    "Boar's Tusk",
    "Fox's Den",
    "Stag's Holt",
    "Sablewood",
    "Umbral Deep",
    "Viridian Maze",
    "Cobalt Shore",
    "Scarlet Wastes",
    "Alabaster Coast",
    "Jade Forest",
    "Amethyst Crag",
    "Pyre Peaks",
    "Frostfall",
    "Stormwatch",
    "Sunward Lands",
    "Moonglimmer Vale",
    "Starfall Wastes",
    "Nightwood",
    "Dawnhaven",
    "Duskfall",
    "Gloomwood",
    "Brightwater",
    "Stillwater Fen",
    "Murkwood",
    "Blackmarsh",
    "Redstone Bluffs",
    "Greymoor",
    "Whitestone",
    "Highgarden",
    "Deepwood",
    "Westmarch",
    "Eastfold",
    "Northwatch",
    "Southgate",
    "Arcanum Theocracy",
    "Lunara Queendom",
    "Terran Republic",
    "Aquila Federation",
    "Ignis Sultanate",
    "Zephyria Union",
    "Sylva Protectorate",
    "Umbra Syndicate",
    "Vorlag Horde",
    "Keldor Barony",
    "Rivia Duchy",
    "Aedirn Kingdom",
    "Lyria Principality",
    "Cintra Regency",
    "Kaedwen Mandate",
    "Redania Electorate",
    "Nilfgaard Empire",
    "Skellige Clans",
    "Temeria Commonwealth",
    "Velen Barony",
    "Novigrad Free City",
    "Mahakam Hold",
    "Brokilon Forest",
    "Zerrikania Satrapy",
    "Toussaint Duchy",
    "Nazair Amirate",
    "Mettina Principality",
    "Angren Kingdom",
    "Verden Jarldom",
    "Talgar Khanate",
    "Cidaris Kingdom",
    "Kovir Monarchy",
    "Hengfors League",
    "Caingorn Kingdom",
    "Malleore March",
    "Geso Duchy",
    "Ebbing Principality",
    "Vicovaro Mandate",
    "Gemmera Satrapy",
    "Etolia Kingdom",
    "Hallowed Theocracy",
    "Iron Dominion",
    "Serene Queendom",
    "Sovereign Republic",
    "Free Federation",
    "Grand Sultanate",
    "Noble Union",
    "Royal Protectorate",
    "Shadowed Syndicate",
    "Savage Horde",
    "Grim Barony",
    "Resplendent Duchy",
    "Ancient Kingdom",
    "Mystic Principality",
    "Silent Regency",
    "Imperial Mandate",
    "Golden Electorate",
    "Vast Empire",
    "United Clans",
    "Free Commonwealth",
    "Wretched Barony",
    "Sunstone Hegemony",
    "Moonshadow Concordat",
    "Starfire Alliance",
    "Aethel Republic",
    "Voros Kingdom",
    "Pyral Empire",
    "Korbin Confederacy",
    "Zentar Union",
    "Myrr Protectorate",
    "Quorva Sovereignty",
    "Valos Queendom",
    "Rhel Principality",
    "Gorn Barony",
    "Lithos Duchy",
    "Nym Shogunate",
    "Karrn Sultanate",
    "Lhazaar Caliphate",
    "Thrane Emirate",
    "Aundair Tsardom",
    "Breland Khanate",
    "Eldeen Reaches",
    "Zilargo Republic",
    "Darguun Nation",
    "Valenar Federation",
    "Talenta Plains",
    "Q'barra Dominion",
    "Droaam Commonwealth",
    "Mror Holds",
    "Kaelen Kingdom",
    "Vesper Theocracy",
    "Orin Protectorate",
    "Lyth Union",
    "Seraph Empire",
    "Draken Confederacy",
    "Gorgon Sovereignty",
    "Helion Queendom",
    "Nyx Principality",
    "Erebus Barony",
    "Tartarus Duchy",
    "Elysium Shogunate",
    "Arcadia Sultanate",
    "Olympos Caliphate",
    "Asgard Emirate",
    "Vanaheim Tsardom",
    "Jotunheim Khanate",
    "Niflheim Republic",
    "Muspelheim Kingdom",
    "Alfheim Empire",
    "Svartalfheim Theocracy",
    "Midgard Dominion",
    "Yggdrasil Confederacy",
    "Valhalla Union",
    "Hel Protectorate",
    "The Aegis State",
    "The Bulwark",
    "The Bastion",
    "The Vanguard",
    "The Concord",
    "The Enclave",
    "The Reach",
    "The Marches",
    "The Pale",
    "The Rift",
    "The Spire",
    "The Citadel",
    "The Nexus",
    "The Core",
    "The Veil",
    "The Expanse",
    "The Void",
    "The Gloom",
    "The Bloom",
    "The Blight",
    "The Scourge",
    "The Forge",
    "The Hearth",
    "The Haven",
    "The Sanctum",
    "The Asylum",
    "The Crucible",
    "The Gauntlet",
    "The Maze",
    "The Labyrinth",
    "The Warren",
    "The Mire",
    "The Fen",
    "The Wastes",
    "The Steppes",
    "The Tundra",
    "The Desert",
    "The Wilds",
    "The Chasm",
    "The Abyss"
];

const CITY_NAMES = [
    "Aerithos",
    "Alabryn",
    "Alderth",
    "Amberwick",
    "Amoria",
    "Anford",
    "Ardelis",
    "Arkenwell",
    "Ashbourne",
    "Ashenwood",
    "Asteron",
    "Athelm",
    "Avenport",
    "Avonlea",
    "Ayreshire",
    "Baelkirk",
    "Bannockwell",
    "Barlwick",
    "Beacontop",
    "Bellamere",
    "Blackpond",
    "Blaineport",
    "Borogard",
    "Brackton",
    "Braemoor",
    "Bramblefort",
    "Bretonia",
    "Brightondale",
    "Brockton",
    "Brookhollow",
    "Bybrook",
    "Caeldon",
    "Caledor",
    "Camelwick",
    "Candlewood",
    "Carden",
    "Carroway",
    "Celestea",
    "Chalkden",
    "Cinderwick",
    "Clarefield",
    "Clayhaven",
    "Clearstone",
    "Cliffside",
    "Cloverton",
    "Coldiron",
    "Coralglen",
    "Cornwallis",
    "Cragmoor",
    "Crestview",
    "Crowglen",
    "Crystalton",
    "Cygnusburg",
    "Dalemore",
    "Darrowick",
    "Dawnbrook",
    "Deepdale",
    "Deerfield",
    "Delmar",
    "Diamondore",
    "Dollington",
    "Drakewater",
    "Duncroft",
    "Duskwood",
    "Dynford",
    "Eagleswath",
    "Ebonfall",
    "Echoire",
    "Eldenhall",
    "Elmford",
    "Emberton",
    "Emeraldine",
    "Everbrook",
    "Everlight",
    "Eyreglen",
    "Faelhaven",
    "Fairmeadow",
    "Falconwood",
    "Fallowden",
    "Fenbridge",
    "Ferndale",
    "Ferrybridge",
    "Fieldhaven",
    "Finchley",
    "Firebrook",
    "Flintwick",
    "Flowerden",
    "Foresthollow",
    "Foxborough",
    "Freehaven",
    "Frostwick",
    "Fulwood",
    "Fyrndell",
    "Gaelin",
    "Garthmere",
    "Gemfall",
    "Glimmerwell",
    "Goldcrest",
    "Gravewood",
    "Greenshire",
    "Greyfang",
    "Grimford",
    "Gryffonwood",
    "Gwyndell",
    "Hallowick",
    "Hamford",
    "Hardwick",
    "Harveston",
    "Hawksworth",
    "Hearthwick",
    "Heatherton",
    "Highgate",
    "Hilderton",
    "Holmwood",
    "Honeybrook",
    "Hylander",
    "Icefall",
    "Idyllia",
    "Illianor",
    "Ironfen",
    "Ironwood",
    "Islebrook",
    "Ivoryton",
    "Jadefield",
    "Jasperton",
    "Jubilee",
    "Juniperwell",
    "Juraven",
    "Kaelburg",
    "Kaelenor",
    "Karnwick",
    "Keltford",
    "Kestrelton",
    "Kilnwick",
    "Kingsley",
    "Knollshire",
    "Labyrinthwick",
    "Lacrima",
    "Lakeview",
    "Larkwood",
    "Leafyford",
    "Lightbourne",
    "Lilacdale",
    "Lindenwick",
    "Lionbrook",
    "Littlefield",
    "Longford",
    "Lowhaven",
    "Lumigard",
    "Lunaris",
    "Lyraxton",
    "Maelor",
    "Maplewick",
    "Marblebrook",
    "Meadowlight",
    "Melliford",
    "Midhaven",
    "Millcroft",
    "Mirthton",
    "Mistyford",
    "Moonhaven",
    "Moorlight",
    "Mossglen",
    "Myrton",
    "Mystwood",
    "Narrowsby",
    "Nettlewood",
    "Newstead",
    "Nightshade",
    "Northford",
    "Norford",
    "Nutmeg",
    "Oakbourne",
    "Oakridge",
    "Oldcross",
    "Oliven",
    "Orchardton",
    "Orinthia",
    "Oryxford",
    "Overton",
    "Palewood",
    "Pebblebrook",
    "Penhurst",
    "Periwinkle",
    "Pinebrook",
    "Placidus",
    "Poppywick",
    "Portside",
    "Providence",
    "Pummelwick",
    "Quarryford",
    "Quellhaven",
    "Quillton",
    "Quiverton",
    "Ravenford",
    "Redwood",
    "Reston",
    "Rhylwick",
    "Ridgegate",
    "Riverhollow",
    "Riverton",
    "Rockhaven",
    "Rosewood",
    "Rundale",
    "Rustford",
    "Sableford",
    "Saltmarsh",
    "Sandford",
    "Sassafras",
    "Shadowood",
    "Shaleglen",
    "Silverbrook",
    "Silvermere",
    "Skyhaven",
    "Sleepyford",
    "Solara",
    "Somerton",
    "Sopwith",
    "Southwick",
    "Spiritwell",
    "Springdale",
    "Starhaven",
    "Stonemarch",
    "Stoneport",
    "Stonyford",
    "Stormreach",
    "Streamhaven",
    "Summerfield",
    "Sunderwick",
    "Sunstone",
    "Sunsetwick",
    "Sweetwater",
    "Sycamore",
    "Tallwood",
    "Tangleton",
    "Thistleford",
    "Thornbrook",
    "Threevale",
    "Timberton",
    "Tinacre",
    "Torhaven",
    "Twilighton",
    "Twinwood",
    "Uldaven",
    "Underford",
    "Uplandwick",
    "Urswick",
    "Valerius",
    "Vanthaven",
    "Vesperia",
    "Victorium",
    "Violette",
    "Vuldor",
    "Wadeford",
    "Wakehurst",
    "Warmwick",
    "Waterglen",
    "Wellhaven",
    "Westford",
    "Whisperingwood",
    "Wildbrook",
    "Willowhaven",
    "Windermere Dale",
    "Windsong",
    "Winterton",
    "Witchford",
    "Wolverton",
    "Woodford",
    "Wyvernwick",
    "Xanador",
    "Xenith",
    "Xylosburg",
    "Yarrowick",
    "Yelloford",
    "Yewford",
    "Yonderland",
    "Yorick",
    "Zephyrton",
    "Zylos",
    "Zingara",
    "Zarthus",
    "Aerie",
    "Arcana",
    "Ashwick",
    "Aura",
    "Bramble",
    "Briar",
    "Cadence",
    "Canyon",
    "Celadon",
    "Cobble",
    "Crest",
    "Dagger",
    "Dahlia",
    "Dartford",
    "Denholm",
    "Drift",
    "Durland",
    "Echos",
    "Elmira",
    "Evers",
    "Fairlight",
    "Falcarragh",
    "Fawn",
    "Fell",
    "Flint",
    "Folkton",
    "Gavel",
    "Gloom",
    "Glimmer",
    "Goldmire",
    "Gore",
    "Greyston",
    "Grimvale",
    "Grove",
    "Harbor",
    "Haven",
    "Haze",
    "Heartwood",
    "Highland",
    "Hollow",
    "Ironpeak",
    "Juniper",
    "Kael",
    "Kithgard",
    "Lagoon",
    "Larkspur",
    "Linden",
    "Lynwood",
    "Marsh",
    "Mirth",
    "Monarch",
    "Mornington",
    "Mossford",
    "Myra",
    "Nadir",
    "Nettle",
    "Nimrod",
    "Nook",
    "Oakwood",
    "Onyx",
    "Orion",
    "Pebble",
    "Pinecone",
    "Pioneer",
    "Quarry",
    "Quince",
    "Rath",
    "Raven",
    "Reach",
    "River",
    "Rookwood",
    "Rosebud",
    "Rust",
    "Saffron",
    "Sage",
    "Sandrift",
    "Sepia",
    "Shade",
    "Shallow",
    "Shirebrook",
    "Silence",
    "Silver",
    "Skylar",
    "Snug",
    "Solace",
    "Sparrow",
    "Spruce",
    "Stark",
    "Steeple",
    "Stoneside",
    "Sunfall",
    "Swallow",
    "Thistle",
    "Thorn",
    "Timber",
    "Topaz",
    "Treetop",
    "Trinity",
    "Vale",
    "Veridia",
    "Vireo",
    "Willow",
    "Windfall",
    "Winterlight",
    "Wolfswood",
    "Woodland",
    "Wren",
    "Wyvern",
    "Xylia",
    "Yarrow",
    "Zella",
    "Zircon",
    "Zora",
    "Aethelred",
    "Bellwood",
    "Caledonia",
    "Dappleton",
    "Eldenglen",
    "Fallowfield",
    "Glimmerwick",
    "Hawthorn",
    "Ironstone",
    "Jadewick",
    "Kilmuir",
    "Larkin",
    "Madrigal",
    "Nightingale",
    "Orchardale",
    "Pyrewood",
    "Quilridge",
    "Rivington",
    "Shadowfen",
    "Thornwood",
    "Underbrook",
    "Valehurst",
    "Whisperton",
    "Xyloton",
    "Yarrowglen",
    "Zenithburg",
    "Aerondale",
    "Blackmarsh",
    "Cinderfield",
    "Deepwater",
    "Elmgrove",
    "Fernfield",
    "Goldwood",
    "Heartford",
    "Ironvale",
    "Jadecrest",
    "Kaelwood",
    "Luminaris",
    "Mystic Falls",
    "Nightwood",
    "Oakhaven Dell",
    "Pinemere",
    "Quillbrook",
    "Ravencrest",
    "Silverpine",
    "Stormcliff",
    "Thistlebrook",
    "Undercliff",
    "Valerondale",
    "Whisperwind",
    "Xylovale",
    "Yewtree",
    "Zephyrcrest",
    "Amberwood",
    "Brightwood",
    "Crystalbrook Hollow",
    "Darkstone",
    "Emberbrook",
    "Frostglen",
    "Glimmerwood",
    "Highvale",
    "Ironhill",
    "Jadevale",
    "Kaelbrook",
    "Luminous Grove",
    "Mistyglade",
    "Northwood",
    "Oldbridge",
    "Pinehollow",
    "Quarryside",
    "Riverglen",
    "Shadowbrook",
    "Thornvale",
    "Underhill",
    "Valebrook",
    "Whispervale",
    "Xyloridge",
    "Yarrowfield",
    "Zemland",
    "Arboreum",
    "Brightonwood",
    "Caelum",
    "Deepglade",
    "Eldara",
    "Faewick",
    "Garthford",
    "Heartsgate",
    "Ironhollow",
    "Jadeport",
    "Kilton",
    "Longview",
    "Mirkstone",
    "Northgate",
    "Oldwick",
    "Pinecroft",
    "Quillhaven",
    "Rivenwood",
    "Silvercrest",
    "Stormdale",
    "Thistlewick",
    "Upton",
    "Valehaven",
    "Whitewick",
    "Xylondale",
    "Yonderwick"
];
